# Generated by Django 5.0.6 on 2024-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_frame_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame_size',
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
